Repository Decide-Part-Utrera/decide-part-utrera-1, pull requests merged in 2022-12, with the labels that each got.

#34 lenguaje-ofensivo-001
  decide/voting/migrations/0004_auto_20221207_1054.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/validators.py
  decide/voting/views.py
Labels: enhancement

#37 Feature/graficasYdescargaDatos-02
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
Labels: visualizer

#38 Feature/modo blanco oscuro
  decide/visualizer/static/styleVisualizer.css
  decide/visualizer/templates/visualizer/visualizer.html
Labels: enhancement

#44 003-feature-footer
  decide/base/templates/base.html
  decide/booth/static/booth/style.css
  decide/visualizer/static/styleVisualizer.css
Labels: bug, enhancement

#45 004-test-selenium-modo-claro-oscuro
  decide/visualizer/test_selenium.py
Labels: test

#47 feature-implements-votings
  decide/voting/migrations/0005_auto_20221210_1903.py
  decide/voting/models.py
  decide/voting/tests.py
  decide/voting/views.py
Labels: enhancement

#48 feature-css-voting-booth-001
  decide/booth/static/booth/style.css
  decide/booth/templates/booth/booth.html
Labels: enhancement

#53 Hotfix/union ramas atrasadas2 - 001
  decide/authentication/serializers.py
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/bot.py
  decide/mensaje_help.txt
  decide/requirements_bot.txt
  decide/store/urls.py
  decide/store/views.py
  decide/testBot.py
  decide/visualizer/admin.py
  decide/visualizer/migrations/0001_initial.py
  decide/visualizer/models.py
  decide/visualizer/serializer.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
  decide/voting/urls.py
  decide/voting/views.py
Labels: enhancement

#56 feature/homepage-1.0
  decide/decide/urls.py
  decide/homepage/static/homepage/estilo.css
  decide/homepage/static/homepage/img/inicio.jpg
  decide/homepage/templates/homepage/homepage.html
  decide/homepage/test_selenium.py
  decide/homepage/urls.py
  decide/homepage/views.py
Labels: enhancement

#57 final-commit-001
  .github/workflows/utrera.yml
  decide/authentication/serializers.py
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/base/static/favicon.ico
  decide/base/templates/base.html
  decide/booth/static/booth/style.css
  decide/booth/templates/booth/booth.html
  decide/bot.py
  decide/decide/urls.py
  decide/homepage/static/homepage/estilo.css
  decide/homepage/static/homepage/img/inicio.jpg
  decide/homepage/templates/homepage/homepage.html
  decide/homepage/test_selenium.py
  decide/homepage/urls.py
  decide/homepage/views.py
  decide/local_settings.gactions.py
  decide/mensaje_help.txt
  decide/store/urls.py
  decide/store/views.py
  decide/testBot.py
  decide/visualizer/admin.py
  decide/visualizer/migrations/0001_initial.py
  decide/visualizer/models.py
  decide/visualizer/serializer.py
  decide/visualizer/static/styleVisualizer.css
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/test_selenium.py
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
  decide/voting/migrations/0004_auto_20221207_1054.py
  decide/voting/migrations/0005_auto_20221210_1903.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/validators.py
  decide/voting/views.py
  requirements.txt
  requirements_bot.txt
  resources/favicon.ico
  vagrant/python.yml
Labels: visualizer, voting, booth, test

#59 final-commit-002
  .github/workflows/utrera.yml
  requirements.txt
  vagrant/Vagrantfile
  vagrant/files/settings.py
  vagrant/python.yml
Labels: enhancement

#63 despliegue-vagrant-001
  requirements.txt
  requirements_bot.txt
  vagrant/Vagrantfile
  vagrant/python.yml
Labels: bug, enhancement

#65 feature-defensa-001
  decide/homepage/templates/homepage/homepage.html
Labels: enhancement
